CREATE TABLE roles(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	role_name VARCHAR(100) NOT NULL

);

CREATE TABLE users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	login VARCHAR(25) NOT NULL,
	password VARCHAR(25) NOT NULL,
	role_id INTEGER NOT NULL,
	FOREIGN KEY(role_id) REFERENCES roles(id)
	ON DELETE SET NULL ON UPDATE NO ACTION
);

CREATE TABLE authors(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	FIO VARCHAR(100) NOT NULL
);


CREATE TABLE genres(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name_genre VARCHAR(100) NOT NULL

);


CREATE TABLE books(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author VARCHAR(100) NOT NULL,
	name_book VARCHAR(100) NOT NULL,
	year_pub INTEGER NOT NULL,
	genre VARCHAR(100) NOT NULL,
	author_id INTEGER NOT NULL,
	genre_id INTEGER NOT NULL,
	FOREIGN KEY(author_id) REFERENCES authors(id),
	FOREIGN KEY(genre_id) REFERENCES genres(id)
	ON DELETE SET NULL ON UPDATE NO ACTION

);


CREATE TABLE books_out(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_book INTEGER NOT NULL,
	date_out VARCHAR(100) NOT NULL,
	date_in VARCHAR(100) NOT NULL,
	FOREIGN KEY(id_book) REFERENCES books(id)
	ON DELETE SET NULL ON UPDATE NO ACTION

);

CREATE TABLE profile(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE Deleted_profile(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	profile_id INTEGER NOT NULL,
	date_deleted DATE NOT NULL,
	details VARCHAR(100) NOT NULL,
	FOREIGN KEY(profile_id) REFERENCES profile(id)
	ON DELETE SET NULL ON UPDATE NO ACTION
);


CREATE TABLE coments(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	profile_id INTEGER NOT NULL,
	date DATE NOT NULL,
	coment VARCHAR(100) NOT NULL,
	FOREIGN KEY(profile_id) REFERENCES profile(id)
	ON DELETE SET NULL ON UPDATE NO ACTION
);


CREATE TABLE Deleted_coments(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	coment_id INTEGER NOT NULL,
	date_deleted DATE NOT NULL,
	details VARCHAR(100) NOT NULL,
	FOREIGN KEY(coment_id) REFERENCES coments(id)
	ON DELETE SET NULL ON UPDATE NO ACTION
);
